version: '3'

networks:
  backend:
  frontend:

services:
  mysql:
    image: mysql:latest
    networks: 
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
  
  php:
    build: ./php
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  
  apache:
    build: ./apache
    depends_on:
      - php
    networks:
      - backend
      - frontend
    volumes:
      - ./public_html/:/var/www/html/
    ports:
      - '8080:80'
